name: Push Tag

on:
  push:
    tags: ['v*']

jobs:

  get_latest_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.latest_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Get latest tag'
        id: latest_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

  dispatch:
    needs: get_latest_tag
    strategy:
      matrix:
        repo: ['OXID-eSales/paypal-module', 'OXID-eSales/module-demoshop-images']
    runs-on: ubuntu-latest
    env:
      TAG: ${{ needs.get_latest_tag.outputs.tag }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: push-tag
          client-payload: '{"tag": "${{ env.TAG }}"}'
